version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: npm start

  functions:
    build: ./functions
    volumes:
      - ./functions:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    command: npm run serve
